add a way to configure the retry policy using json file.
vert-x3/vertx-zookeeper pull request #143
Opened 2023-06-01 09:25 UTC by vmorsiani

Motivation:

Right now the RetryPolicy is hardcoded (ExponentialBackoffRetryPolicy) and the only way to override this is buy providing directly a CuratorFramework instance when creating a ZookeeperClusterManager.

It is a bit overkill to do so when someone simply want to change the retry policy (for something like retry forever for retry elapsed or retry forever for example).

This pull request provide a simple mechanism to enable a user to provide a "policy" setting within the retry configuration, which will then be used in the ZookeeperClusterManager

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

2023-06-07 16:03 UTC, tsegismont reviewed
Thank you @vmorsiani .

Can you please:

- add a test for `RetryPolicyHelper`
-  update the documentation

After the PR is merged, I'll backport this to 4.x

2023-06-22 08:46 UTC, tsegismont requested changes
Thank you @vmorsiani , just a couple of documentation changes required

2023-06-22 10:03 UTC, vmorsiani commented
> Thank you @vmorsiani , just a couple of documentation changes required

Thanks for the feedback @tsegismont 
I integrated your documentation changes so I believe it should be all good now.

2023-07-03 08:51 UTC, tsegismont approved these changes
Thank you @vmorsiani , I'll backport this to 4.x

2023-07-03 08:51 UTC, merged